Repository AY2021S2-CS2103T-T11-3/tp, pull requests merged in 2021-03, with the labels that each got.

#42 V1.2 Add search for contacts from a specified school
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/person/SchoolContainsKeywordsPredicate.java
Labels: priority.Medium, type.Story

#63 Update GUI to improve information storing v1.3
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DetailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DetailCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/tutorspet.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetails.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DetailCommandTest.java
  src/test/java/seedu/address/logic/parser/DetailCommandParserTest.java
Labels: priority.Medium, type.Story

#64 v1.3 Fix GUI display & Add detail command into user guide
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetails.fxml
Labels: bug, priority.Low, type.Story

#68 v1.3 Fix error when typing command
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug, priority.Low, type.Story

#71 V1.3 Update DetailCommand and Diagrams in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/DetailActivityDiagram.puml
  docs/diagrams/DetailSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/DetailActivityDiagram.png
  docs/images/DetailSequenceDiagram.png
Labels: documentation, priority.Medium, type.DG

#110 Fix bugs in index of important dates
  src/main/java/seedu/address/logic/commands/DeleteDateCommand.java
Labels: bug

#109 Update documentations v1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  src/main/java/seedu/address/ui/PersonDetails.java
Labels: documentation

#122 Add enum subjects
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/subject/AvailableSubject.java
  src/main/java/seedu/address/model/subject/Subject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation, enhancement, type.Story
