Repository AY2021S2-CS2103T-T11-3/tp, pull requests merged in 2021-04, with the labels that each got.

#127 Update UserGuide
  docs/UserGuide.md
Labels: documentation

#185 Fix Undocumented Feature
  docs/UserGuide.md
Labels: documentation

#186 Fix UG Coming soon formatting issue
  docs/UserGuide.md
Labels: bug

#187 Fix UG Editing the data file
  docs/UserGuide.md
Labels: bug, documentation

#188 Fix detail feature
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/person/predicate/LessonPersonPredicate.java
  src/main/java/seedu/address/ui/DetailLessonListCard.java
  src/main/java/seedu/address/ui/DetailLessonListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/resources/view/DetailLessonListCard.fxml
  src/main/resources/view/PersonDetails.fxml
Labels: bug

#189 Fix checkstyle issue
  docs/UserGuide.md
Labels: bug, documentation

#190 Fix scheduling and important date size issue
  src/main/resources/view/ImportantDatesWindow.fxml
  src/main/resources/view/ScheduleWindow.fxml
Labels: bug, priority.Medium

#191 Fix UG Tip bullet points format
  docs/UserGuide.md
Labels: bug, documentation

#192 Fix UG Tip bullet points format
  docs/UserGuide.md
Labels: bug, documentation

#218 Fix UG documentation errors.
  docs/UserGuide.md
Labels: documentation

#223 V1.4 Update GUI
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetails.fxml
Labels: enhancement

#224 Fix GUI
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetails.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: bug

#228 Fix GUI
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetails.fxml
Labels: enhancement

#230 Details gui enhancement
  src/main/java/seedu/address/model/person/level/Level.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/resources/images/profile.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonDetails.fxml
Labels: bug, enhancement

#236 Update developers guide for important dates feature
  docs/DeveloperGuide.md
  docs/diagrams/AddImportantDateActivityDiagram.puml
  docs/diagrams/AddImportantDateSequenceDiagram.puml
  docs/diagrams/DeleteImportantDateActivityDiagram.puml
  docs/diagrams/DeleteImportantDateSequenceDiagram.puml
  docs/diagrams/ListImportantDatesActivityDiagram.puml
  docs/diagrams/ListImportantDatesSequenceDiagram.puml
  docs/images/AddImportantDateActivityDiagram.png
  docs/images/AddImportantDateSequenceDiagram.png
  docs/images/DeleteImportantDateActivityDiagram.png
  docs/images/DeleteImportantDateSequenceDiagram.png
  docs/images/ListImportantDatesActivityDiagram.png
  docs/images/ListImportantDatesSequenceDiagram.png
Labels: documentation

#244 Fix Detail GUI
  src/main/resources/view/PersonDetails.fxml
Labels: bug

#258 Fix CommandBox sizing
  src/main/resources/view/MainWindow.fxml
Labels: bug

#272 fix last prefix, other UG bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/LevelDownCommandParser.java
  src/main/java/seedu/address/logic/parser/LevelUpCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
Labels: bug

#281 Add zongyu's PPP
  docs/team/internityz.md
  docs/team/johndoe.md
Labels: documentation

#282 Update dg features
  docs/DeveloperGuide.md
  docs/diagrams/LevelDownActivityDiagram.puml
  docs/diagrams/LevelDownSequenceDiagram.puml
  docs/diagrams/LevelUpActivityDiagram.puml
  docs/diagrams/LevelUpSequenceDiagram.puml
  docs/diagrams/ListImportantDatesActivityDiagram.puml
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/LevelDownActivityDiagram.png
  docs/images/LevelDownSequenceDiagram.png
  docs/images/LevelUpActivityDiagram.png
  docs/images/LevelUpSequenceDiagram.png
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
Labels: documentation, type.DG

#309 Fix GUI scalability issue and limt input size
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/PersonDetails.fxml
Labels: bug

#312 Insert examples into tables and Add return table of contents
  docs/UserGuide.md
Labels: documentation, type.UG

#313 Fix detail example table
  docs/UserGuide.md
Labels: bug, documentation, type.UG

#314 Fix table of contents display
  docs/UserGuide.md
Labels: bug

#316 Fix button not appearing
  docs/UserGuide.md
Labels: bug, type.UG

#319 check last prefix
  src/main/java/seedu/address/logic/commands/DeleteDateCommand.java
  src/main/java/seedu/address/logic/commands/DetailCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: bug

#331 Navigate UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#334 added subject, change lv to case insensitive
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/level/Level.java
  src/main/java/seedu/address/model/subject/AvailableSubject.java
Labels: bug

#335 Fix word limit and Detail GUI
  src/main/java/seedu/address/model/person/Name.java
  src/main/resources/view/PersonDetails.fxml
Labels: bug

#337 Add limit for phone and school name
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/School.java
  src/main/resources/view/PersonDetails.fxml
Labels: bug

#338 Add screenshot for detail command
  docs/UserGuide.md
  docs/images/detail command.png
Labels: documentation

#339 UG add demo photos
  docs/UserGuide.md
  docs/images/DemoAfterAddCommand.png
  docs/images/DemoAfterEditCommand.png
  docs/images/DemoBeforeAddCommand.png
  docs/images/DemoBeforeEditCommand.png
Labels: documentation

#346 Fix hyperlink error in UG
  docs/UserGuide.md
Labels: documentation

#347 Update DG UI diagram and Add return button
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: documentation

#350 Update UIClassDiagram image
  docs/images/UiClassDiagram.png
Labels: documentation

#359 Update UIClassDiagram image
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  src/main/resources/view/MainWindow.fxml
Labels: bug

#361 Update GUI Scalability
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetails.fxml
Labels: bug

#364 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/ui/Card/DateCard.java
  src/main/java/seedu/address/ui/Card/DetailLessonListCard.java
  src/main/java/seedu/address/ui/Card/LessonListCard.java
  src/main/java/seedu/address/ui/Card/PersonCard.java
  src/main/java/seedu/address/ui/ImportantDatesWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PanelList/DateListPanel.java
  src/main/java/seedu/address/ui/PanelList/DetailLessonListPanel.java
  src/main/java/seedu/address/ui/PanelList/LessonListPanel.java
  src/main/java/seedu/address/ui/PanelList/PersonListPanel.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/java/seedu/address/ui/ScheduleWindow.java
Labels: documentation, type.DG

#374 Add glossary, add example screenshots, fix bugs
  docs/UserGuide.md
  docs/images/DemoLevelDownCommand.png
  docs/images/DemoLevelUpCommand.png
  docs/images/DemoSortCommand.png
  docs/images/TutorsPetDiagram1.png
  docs/images/TutorsPetDiagram2.png
Labels: type.UG

#391 Fix UG pictures
  docs/UserGuide.md
  docs/images/DemoAddDateCommand.png
  docs/images/DemoAfterAddCommand.png
  docs/images/DemoAfterDeleteCommand.png
  docs/images/DemoAfterDetailCommand.png
  docs/images/DemoAfterEditCommand.png
  docs/images/DemoAfterLevelDownCommand1.png
  docs/images/DemoAfterLevelDownCommand2.png
  docs/images/DemoAfterLevelUpCommand1.png
  docs/images/DemoAfterLevelUpCommand2.png
  docs/images/DemoAfterSearchCommand.png
  docs/images/DemoBeforeAddCommand.png
  docs/images/DemoBeforeDeleteCommand.png
  docs/images/DemoBeforeDetailCommand.png
  docs/images/DemoBeforeEditCommand.png
  docs/images/DemoBeforeLevelDownCommand1.png
  docs/images/DemoBeforeLevelDownCommand2.png
  docs/images/DemoBeforeLevelUpCommand1.png
  docs/images/DemoBeforeLevelUpCommand2.png
  docs/images/DemoBeforeSearchCommand.png
  docs/images/DemoDeleteDateCommand.png
  docs/images/DemoLevelUpCommand.png
  docs/images/DemoListDateCommand.png
  docs/images/DemoSortCommand.png
  docs/images/Search Command.png
  docs/images/add-date command.png
  docs/images/delete command.png
  docs/images/delete-date command.png
  docs/images/detail command.png
  docs/images/list-date command.png
  src/main/resources/view/PersonDetails.fxml
Labels: documentation, type.UG

#397 Add UG search command picture
  docs/UserGuide.md
  docs/images/DemoAfterSearchCommand2.png
Labels: documentation

#411 Update PPP
  docs/UserGuide.md
  docs/images/DemoAfterSearchCommand.png
  docs/images/DemoAfterSearchCommand1.png
  docs/team/chenzaza.md
  docs/team/internityz.md
Labels: documentation
